language: java

jdk:
  - oraclejdk7
#  - openjdk7
#  - openjdk6

# script: python etc/travis-build.py --settings ~/.m2/sonatype.xml

# after_success:
#  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura

after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura
#  - mvn clean test jacoco:report coveralls:jacoco
